spring:
  datasource:
    url: jdbc:mysql://luna-database-1.cla2o6s40pfp.ap-northeast-2.rds.amazonaws.com:3306/dailyharu?readOnly=false
    # url: jdbc:mysql://localhost:3307/dailyharu
    username: admin
    password: minjim3729
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
 
  security:
    jwt:
      secret: ${JWT_SECRET:dailyharusecretkey1234567890dailyharusecretkey1234567890} # TODO: 보안 취약점 해결 필요
      expiration: 86400000 # 24시간
      refresh-expiration: 604800000 # 7일

  mail:
    host: smtp.gmail.com
    port: 587
    username: minfrankdev
    password: tdefxbdeworwnvnb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000
          write-timeout: 5000
server:
  port: 8080
  # HTTPS 설정은 개발 환경에서 필요한 경우 주석 해제
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ${SSL_KEY_STORE_PASSWORD:amsams12!@}
    key-store-type: PKCS12
  
logging:
  file:
    name: /home/ec2-user/dailyharu/logs/application.log
  level:
    org.springframework.security: INFO
    com.minfrank.dailyharu: INFO 